
---
- hosts: web
  tasks:
  - name: install nginx
    become: yes
    apt:
      name: nginx
      state: present
  - name: make nginx run
    become: yes
    service:
      name: nginx
      state: started
  - name: open 80
    become: yes
    firewalld:
      service: nginx
      permanent: true
      state: enabled
  - name: restart firewall
    become: yes
    service:
      name: firewalld
      state: restarted
