
- hosts: db
  become: true
  gather_facts: false

  tasks:

  - name: Run the equivalent of "apt-get update"
    apt:
      update_cache: yes

  - name: Install MariaDB
    apt:
      name={{item}}
      state=present
      update_cache=yes
    with_items:
      - mariadb-client
      - mariadb-common
      - mariadb-server

  - name: Start MariaDB service
    service:
      name: mysql
      state: restarted

  - name: 
